### ISSUE TITLE
can you help about cso2?

### ISSUE THREAD

**Issue by IGNRexI** [Ekey/MD.PKG.Tool#1]
"We're working with Cso2 and we have some issues we're stuck on. Can you provide paid/unpaid support? At least some logical support would be helpful. Our Discord address is: https://discord.gg/cso2"

**Comment by Ekey** [comment]
Have you checked [this](https://forum.xentax.com/viewtopic.php?f=10&t=11640)?

**Comment by IGNRexI** [comment]
Can we talk about pkg back compression?

**Comment by Ekey** [comment]
You mean repack pkg's?
